### PR TITLE
exit gracefully when interrupted

### LINKED ISSUE #24: Ctrl-C fails to kill perf run
On macOS, I press <kbd>Ctrl-C</kbd> while a perf run is going and one of the following situations will happen:

- ✅ Script will stop and any instance of Code will exit
- 🐛 Code will exit but script won't really return to shell
- 🐛 Script will return to shell but Code will stay running in a hanged state, I have to Force Quit it

### PR DESCRIPTION
**Pull request by sandy081**
fix #24

exit gracefully when interrupted

### CODE REVIEW

File: src/perf.ts [hunk 1]
```diff
@@ -55,6 +55,7 @@ export async function launch(options: Options) {
 		let timedOut = false;
 		let promise: Promise<string | undefined>;
 		const abortController = new AbortController();
+		process.on('SIGINT', () => abortController.abort());
```
Comment (connor4312) [inline src/perf.ts:58]: Not sure if it's a concern in this context, but you may want to make sure to remove this listener later on, since the present of any listener for SIGINT will prevent the default exit behavior (i.e. even after this function returns)

**Review by connor4312 — APPROVED** [review]

**Review by joaomoreno — APPROVED** [review]
